### ISSUE TITLE
[Fix] Making port an integer

### ISSUE THREAD

**Issue by mansimov** [JulesGM/ParlAI_SearchEngine#1]
Thanks for making this repo!

I have been using it and noticed that I needed to make a small fix to make it work.

Need to convert port to integer otherwise it will throw an error.

```
def _parse_host(host: str) -> Tuple[str, str]:
    splitted = host.split(":")
    hostname = splitted[0]
    port = splitted[1] if len(splitted) > 1 else _DEFAULT_PORT
    port = int(port) # port is integer
    return hostname, port
```

**Comment by hitchingsh** [comment]
I got the exact same error and the fix above allowed me to get the search server working. Thank you.

**Comment by JulesGM** [comment]
Thanks @mansimov, pushed the fix.
