### ISSUE TITLE
working fine cmd & not working webpage 501

### ISSUE THREAD

**Issue by daje0601** [JulesGM/ParlAI_SearchEngine#14]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/73736988/176848200-e0673a2a-6d1a-4fac-90ad-87901148b3fa.png">

As above, in cmd, the url address is output, but the error "code 501, message Unsupported method ('GET')" occurs. Why are you doing this?

**Comment by JulesGM** [comment]
I haven't used this code in quite some time

**Comment by daje0601** [comment]
I solve this problem! Thank you!
