### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by hitchingsh** [JulesGM/ParlAI_SearchEngine#3]
I still need lxml and chardet to run so it would be great if you could add it to the requirements

When I do the query:

curl -X POST "http://0.0.0:8090" -d "q=Wandavision&n=5"

it crashes the search_server.py and to fix it I added the line so if the title is non existant it does not crash

    if output_dict["title"]:
        output_dict["title"] = output_dict["title"].replace("\n", "").replace("\r", "")

Note, this error also crashes blenderbot2 and you can reproduce it by typing the following sentence into blenderbot2 while using your search_server.py

I like the TV show Wandavision

Note, I have made and tested this fix for both of the cases above and both now work properly.  Can you make this to your github?

PS: Thank you so much for writing this server! It's been a life saver.

**Comment by JulesGM** [comment]
Thanks for filing, Fixed.
