### ISSUE TITLE
Failed To Connect To Port

### ISSUE THREAD

**Issue by Jawad1347** [JulesGM/ParlAI_SearchEngine#9]
While chatting with blenderbot with the $HOST search_server it stopped taking inputs after a while and when I checked with the command
> !curl -X POST $HOST -d "q=biggest gpt model&n=1"

it threw the error
>> curl: (7) Failed to connect to 0.0.0.0 port 1111: Connection refused

**Comment by JulesGM** [comment]
Did you try resetting the server with a different port? it could be all kinds of stuff specific to your os, what is running on it, etc

**Comment by Jawad1347** [comment]
Thank you I forgot to close it.
